POST /residents/8/familyRelationshipCode
Host: localhost:8080
Content-Type: application/json

{
  "familySerialNumber": 9,
  "familyRelationshipCode": "부"
}

###
PUT /residents/8/familyRelationshipCode/9
Host: localhost:8080
Content-Type: application/json

{
  "familyRelationshipCode": "모"
}

###
DELETE /residents/8/familyRelationshipCode/9
Host: localhost:8080
Content-Type: application/json